general {
    hide_cursor = true
}

background {
    path = /home/greg/pictures/neon_mountain.jpg
    blur_passes = 0
}

input-field {
    size = 300, 50
    position = 0, 20
    dots_center = true
}
